openapi: 3.0.0
info:
  title: Movie Ticket Booking API
  description: This API allows customers to book movie tickets online and process payments.
  version: 1.0.0

paths:
  /movies:
    get:
      summary: Movie times available
      description: Available movies and movie times are retrieved
      parameters:
        - name: date
          in: query
          description: Date to retrieve movie times for (format: YYYY-MM-DD).
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of available movies and showtimes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    items:
                      type: object
                      properties:
                        movie_name:
                          type: string
                          example: "Inception"
                        showtimes:
                          type: array
                          items:
                            type: string
                            example: "18:00"
        '404':
          description: No movies found for the given date.
  
  /seats:
    post:
      summary: Reserve a seat for the movie
      description: Seat is reserved for a specific movie and time of movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_name:
                  type: string
                  example: "Inception"
                showtime:
                  type: string
                  example: "18:00"
                seat_number:
                  type: string
                  example: "A10"
              required:
                - movie_name
                - showtime
                - seat_number
      responses:
        '200':
          description: Seat reserved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Seat A10 reserved successfully."
        '400':
          description: Bad request (missing or invalid parameters).

  /reservations/{reservation_id}:
    delete:
      summary: Cancel payment
      description: Cancel payment by cancelling movie ticket reservation
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Unique ID for movie ticket reservation.
          schema:
            type: string
            example: "res12345"
      responses:
        '200':
          description: Reservation canceled successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Reservation res12345 canceled successfully."
        '404':
          description: Reservation ID not found.
        '500':
          description: Server error during cancellation.
